title: Daniele Bonetta
url: "https://danielebonetta.info"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: "G-7356B8NJ89"

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Research"
   link: "research"
 - name: "Teaching" 
   link: "teaching"
#  - name: "Students"
#    link: "students"
 - name: "Contact"
   link: "contact"
#  - name: "Random"
#    link: "random"